# Generated by Django 5.1.1 on 2024-11-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
